CREATE DATABASE BANCOS;

USE BANCOS;

CREATE TABLE CLIENTES 
    ( 
     cedula VARCHAR (15)  NOT NULL , 
     nombre VARCHAR (30)  NOT NULL , 
     ciudad VARCHAR (30)  NOT NULL , 
     telefono VARCHAR (15)  NOT NULL 
    );

CREATE TABLE CLI_CUENTAS 
    ( 
     ced_cliente VARCHAR (15)  NOT NULL , 
     nro_cuenta INTEGER  NOT NULL 
    );

CREATE TABLE CLI_PRESTAMOS 
    ( 
     ced_cliente VARCHAR (15)  NOT NULL , 
     nro_prestamo INTEGER  NOT NULL 
    );

CREATE TABLE CUENTAS 
    ( 
     nro_cuenta INTEGER  NOT NULL , 
     saldo REAL  NOT NULL , 
     cod_suc INTEGER  NOT NULL 
    );

CREATE TABLE PRESTAMOS 
    ( 
     nro_prestamo INTEGER  NOT NULL , 
     valor REAL  NOT NULL , 
     saldo REAL  NOT NULL , 
     cod_suc INTEGER  NOT NULL 
    );

CREATE TABLE SUCURSALES 
    ( 
     codigo INTEGER  NOT NULL , 
     nombre VARCHAR (30)  NOT NULL , 
     ciudad VARCHAR (30)  NOT NULL , 
     activo REAL  NOT NULL 
    );
CREATE TABLE TRANSACCIONES(
id_transaccion int NOT NULL,
tipo_transaccion varchar(20) NOT NULL,
fecha_transaccion date NOT NULL,
monto int NOT NULL,
cuenta_origen int NOT NULL,
cuenta_destino int NOT NULL,
PRIMARY KEY (id_transaccion));

ALTER TABLE TRANSACCIONES
    ADD CONSTRAINT FK_cuenORIG FOREIGN KEY(cuenta_origen) 
    REFERENCES CUENTAS(nro_cuenta);
    
ALTER TABLE TRANSACCIONES
    ADD CONSTRAINT FK_cuenDEST FOREIGN KEY(cuenta_destino) 
    REFERENCES CUENTAS(nro_cuenta);
    
ALTER TABLE PRESTAMOS 
    ADD CONSTRAINT PRESTAMO_PK PRIMARY KEY ( nro_prestamo ) ;
    
ALTER TABLE CUENTAS 
    ADD CONSTRAINT CUENTA_PK PRIMARY KEY ( nro_cuenta ) ;
    
ALTER TABLE CLI_PRESTAMOS 
    ADD CONSTRAINT CLI_PRES_PK PRIMARY KEY ( ced_cliente, nro_prestamo ) ;

ALTER TABLE CLI_CUENTAS 
    ADD CONSTRAINT CLI_CUENTA_PK PRIMARY KEY ( nro_cuenta, ced_cliente ) ;

ALTER TABLE CLIENTES 
    ADD CONSTRAINT CLIENTE_PK PRIMARY KEY (cedula ) ;
    
ALTER TABLE SUCURSALES 
    ADD CONSTRAINT SUCURSAL_PK PRIMARY KEY ( codigo ) ;

ALTER TABLE CLI_CUENTAS 
    ADD CONSTRAINT CLI_CUENTA_CLIENTE_FK FOREIGN KEY(ced_cliente) 
    REFERENCES CLIENTES 
    (cedula);

ALTER TABLE CLI_CUENTAS 
    ADD CONSTRAINT CLI_CUENTA_CUENTA_FK FOREIGN KEY(nro_cuenta) 
    REFERENCES CUENTAS (nro_cuenta);

ALTER TABLE CLI_PRESTAMOS 
    ADD CONSTRAINT CLI_PRES_CLIENTE_FK FOREIGN KEY (ced_cliente) 
    REFERENCES CLIENTES(cedula);

ALTER TABLE CLI_PRESTAMOS 
    ADD CONSTRAINT CLI_PRES_PRESTAMO_FK FOREIGN KEY(nro_prestamo) 
    REFERENCES PRESTAMOS (nro_prestamo);

ALTER TABLE CUENTAS 
    ADD CONSTRAINT CUENTA_SUCURSAL_FK FOREIGN KEY(cod_suc) 
    REFERENCES SUCURSALES(codigo);

ALTER TABLE PRESTAMOS 
    ADD CONSTRAINT PRESTAMO_SUCURSAL_FK FOREIGN KEY(cod_suc)
    REFERENCES SUCURSALES(codigo);

